name: Lint and Vet Backend Code

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Install linter
        run: go get -u golang.org/x/lint/golint
        
      - name: Run vet & lint
        run: |
          go vet .
          golint .
